[package]
name = "collatz-rs"
version = "0.1.0"
authors = ["Lenny Händler <lenny@lennyhaendler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rayon = "1.1"